# Generated by Django 6.0 on 2026-02-14 01:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=255)),
                ('cpf_owner', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='CPF deve ter 11 dígitos', regex='^\\d{11}$')])),
                ('name_in_card', models.CharField(max_length=255)),
                ('card_number', models.CharField(max_length=16)),
                ('expires_month', models.CharField(max_length=2)),
                ('expires_year', models.CharField(max_length=4)),
                ('cvv', models.CharField(max_length=4)),
                ('user_id', models.IntegerField()),
            ],
        ),
    ]
