# Generated by Django 6.0 on 2026-02-14 02:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Card', '0002_cardmodel_created_at_cardmodel_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardmodel',
            name='user_id',
        ),
        migrations.AddField(
            model_name='cardmodel',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cards_list', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
