# Generated by Django 6.0 on 2026-02-15 01:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Card', '0003_remove_cardmodel_user_id_cardmodel_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cardmodel',
            options={'ordering': ['-created_at'], 'verbose_name': 'Cartão', 'verbose_name_plural': 'Cartões'},
        ),
        migrations.AlterField(
            model_name='cardmodel',
            name='card_number',
            field=models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(message='Número de cartão inválido', regex='^\\d{13,16}$')]),
        ),
        migrations.AlterField(
            model_name='cardmodel',
            name='cpf_owner',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='CPF deve ter 11 dígitos', regex='^\\d{11}$')], verbose_name='CPF do Titular'),
        ),
        migrations.AlterField(
            model_name='cardmodel',
            name='cvv',
            field=models.CharField(max_length=4, verbose_name='CVV'),
        ),
        migrations.AlterField(
            model_name='cardmodel',
            name='expires_month',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Mês de Expiração'),
        ),
        migrations.AlterField(
            model_name='cardmodel',
            name='expires_year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(2026)], verbose_name='Ano de Expiração'),
        ),
        migrations.AlterField(
            model_name='cardmodel',
            name='name_in_card',
            field=models.CharField(max_length=255, verbose_name='Nome no Cartão'),
        ),
        migrations.AlterField(
            model_name='cardmodel',
            name='owner_name',
            field=models.CharField(max_length=255, verbose_name='Nome do Titular'),
        ),
    ]
