# Generated by Django 5.0.6 on 2024-06-16 18:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AddressModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=255)),
                (
                    "country",
                    models.CharField(
                        max_length=200,
                        validators=[django.core.validators.MinLengthValidator(3)],
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        max_length=200,
                        validators=[django.core.validators.MinLengthValidator(3)],
                    ),
                ),
                (
                    "zip",
                    models.CharField(
                        max_length=20,
                        validators=[django.core.validators.MinLengthValidator(3)],
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        max_length=200,
                        validators=[django.core.validators.MinLengthValidator(3)],
                    ),
                ),
                (
                    "receiver_name",
                    models.CharField(
                        max_length=200,
                        validators=[django.core.validators.MinLengthValidator(3)],
                    ),
                ),
                (
                    "receiver_cpf",
                    models.CharField(
                        max_length=11,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="CPF deve ter 11 dígitos", regex="^\\d{11}$"
                            )
                        ],
                    ),
                ),
            ],
        ),
    ]
