# Generated by Django 6.0 on 2026-02-14 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Companies', '0001_initial'),
        ('UsersAccounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='UsersAccounts.usermodel'),
        ),
        migrations.AlterUniqueTogether(
            name='companyproductline',
            unique_together={('company', 'product')},
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('user', 'product_line')},
        ),
    ]
