# Generated by Django 6.0 on 2026-02-14 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('PIX', 'PIX'), ('boleto', 'Boleto'), ('cartao', 'Cartão')], max_length=10, verbose_name='Método de pagamento')),
                ('status', models.CharField(choices=[('accepted', 'Accepted'), ('pending', 'Pending'), ('declined', 'Declined'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('canceled', 'Canceled')], max_length=10, verbose_name='Status do pedido')),
                ('installments', models.IntegerField(default=1, verbose_name='Parcelas')),
                ('pix_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='Código PIX para pagamento')),
                ('bar_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='Código de barras do boleto para pagamento')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
            },
        ),
        migrations.CreateModel(
            name='ProductLineModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantidade')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Itens',
            },
        ),
    ]
