# Generated by Django 6.0 on 2026-02-14 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Address', '0001_initial'),
        ('Card', '0001_initial'),
        ('Companies', '0002_initial'),
        ('Orders', '0001_initial'),
        ('Products', '0001_initial'),
        ('UsersAccounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='orders_as_buyer', to='UsersAccounts.usermodel', verbose_name='Comprador'),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='card_pay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Card.cardmodel', verbose_name='Cartão de pagamento'),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='order_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Address.addressmodel', verbose_name='Endereço de entrega'),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='orders_as_seller', to='Companies.companymodel', verbose_name='Vendedor'),
        ),
        migrations.AddField(
            model_name='productlinemodel',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Products.productmodel', verbose_name='Produto'),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='products',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='items', to='Orders.productlinemodel', verbose_name='Produtos'),
        ),
    ]
