# Generated by Django 6.0 on 2026-02-14 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome do produto')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição do produto')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço')),
                ('category', models.CharField(choices=[('EL', 'Electronics & Technology'), ('FA', 'Fashion & Accessories'), ('HK', 'Home & Kitchen'), ('BC', 'Beauty & Personal Care'), ('SO', 'Sports & Outdoors'), ('BK', 'Baby & Kids'), ('HW', 'Health & Wellness'), ('BM', 'Books & Media'), ('FB', 'Food & Beverages'), ('AT', 'Automotive & Tools'), ('PS', 'Pet Shop'), ('OG', 'Outdoors & Gardening')], default='EL', max_length=2, verbose_name='Categoria')),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Atual')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Desconto')),
                ('last_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Último Preço')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['name'],
            },
        ),
    ]
