# Generated by Django 6.0 on 2026-02-15 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='current_price',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='last_price',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='price',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Preço Base'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Desconto'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Imagem do Produto'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='sku',
            field=models.CharField(default='TEMP-SKU', max_length=50, unique=True, verbose_name='SKU/Código'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
